app_name:
  type: string
  default: "myapp"
  description: Название приложения

port:
  type: int
  default: 8080
  description: Порт сервера

enable_feature:
  type: bool
  default: true
  description: feature flag

thresholds:
  type: "map[string]int"
  default:
    warning: 70
    critical: 90
  description: Пороговые значения

timeout:
  type: duration
  default: "5s"
  description: Таймаут ожидания ответа от сервиса


auth_required_methods:
  type: "map[string]struct{}"
  default:
    /api/user/profile: {}
    /api/user/settings: {}
    /api/orders/create: {}
  description: Методы, требующие аутентификации