app_name:
  type: string
  default: "my-app"
  description: Название приложения

max_retries:
  type: int
  default: 5
  description: Максимальное число попыток

debug:
  type: bool
  default: false
  description: Включение режима отладки

servers:
  type: "[]string"
  default:
    - server1
    - server2
  description: Список серверов

thresholds:
  type: "map[string]int"
  default:
    cpu: 80
    memory: 70
  description: Пороговые значения

labels:
  type: "map[string]string"
  default:
    env: production
    region: us-east-1
  description: Метки окружения
