// Code generated by config-gen; DO NOT EDIT.
package config

import (
	"time"
)

type FakeAppConfig struct {
	enableFeature       bool
	thresholds          map[string]int
	timeout             time.Duration
	authRequiredMethods map[string]struct{}
	appName             string
	port                int
}

// GetEnableFeature возвращает значение enable_feature. feature flag
func (f *FakeAppConfig) GetEnableFeature() bool {
	return f.enableFeature
}

// GetThresholds возвращает значение thresholds. Пороговые значения
func (f *FakeAppConfig) GetThresholds() map[string]int {
	return f.thresholds
}

// GetTimeout возвращает значение timeout. Таймаут ожидания ответа от сервиса
func (f *FakeAppConfig) GetTimeout() time.Duration {
	return f.timeout
}

// GetAuthRequiredMethods возвращает значение auth_required_methods. Методы, требующие аутентификации
func (f *FakeAppConfig) GetAuthRequiredMethods() map[string]struct{} {
	return f.authRequiredMethods
}

// GetAppName возвращает значение app_name. Название приложения
func (f *FakeAppConfig) GetAppName() string {
	return f.appName
}

// GetPort возвращает значение port. Порт сервера
func (f *FakeAppConfig) GetPort() int {
	return f.port
}
