// Code generated by generator; DO NOT EDIT.
package config

type FakeAppConfig struct {
	appName    string
	maxRetries int
	debug      bool
	servers    []string
	thresholds map[string]int
	labels     map[string]string
}

// GetAppName возвращает значение app_name. Название приложения
func (f *FakeAppConfig) GetAppName() string {
	return f.appName
}

// GetMaxRetries возвращает значение max_retries. Максимальное число попыток
func (f *FakeAppConfig) GetMaxRetries() int {
	return f.maxRetries
}

// GetDebug возвращает значение debug. Включение режима отладки
func (f *FakeAppConfig) GetDebug() bool {
	return f.debug
}

// GetServers возвращает значение servers. Список серверов
func (f *FakeAppConfig) GetServers() []string {
	return f.servers
}

// GetThresholds возвращает значение thresholds. Пороговые значения
func (f *FakeAppConfig) GetThresholds() map[string]int {
	return f.thresholds
}

// GetLabels возвращает значение labels. Метки окружения
func (f *FakeAppConfig) GetLabels() map[string]string {
	return f.labels
}
