// Code generated by config-gen; DO NOT EDIT.
package config

import (
	"time"
)

type FakeAppConfig struct {
	MaxRetries          int
	EnableFeature       bool
	BatchSize           int
	Timeout             time.Duration
	AuthRequiredMethods map[string]struct{}
}

// GetMaxRetries возвращает значение max_retries. Максимальное число попыток
func (f *FakeAppConfig) GetMaxRetries() int {
	return f.MaxRetries
}

// GetEnableFeature возвращает значение enable_feature. feature flag
func (f *FakeAppConfig) GetEnableFeature() bool {
	return f.EnableFeature
}

// GetBatchSize возвращает значение batch_size. Размер батча
func (f *FakeAppConfig) GetBatchSize() int {
	return f.BatchSize
}

// GetTimeout возвращает значение timeout. Таймаут ожидания ответа от сервиса
func (f *FakeAppConfig) GetTimeout() time.Duration {
	return f.Timeout
}

// GetAuthRequiredMethods возвращает значение auth_required_methods. Auth required
func (f *FakeAppConfig) GetAuthRequiredMethods() map[string]struct{} {
	return f.AuthRequiredMethods
}
